### ISSUE TITLE
Creating too many newlines in resulting output

### ISSUE THREAD

**Issue by krf** [MacroBull/html2zim#1]
For example, the following HTML code:

```
<ul>
<li>wl_egl_window_create()</li>
<li>wl_egl_window_destroy()</li>
<li>wl_egl_window_resize()</li>
<li>wl_egl_window_get_attached_size()</li>
</ul>
```

... gets converted into:

```
    *   wl_egl_window_create()

    *   wl_egl_window_destroy()

    *   wl_egl_window_resize()

    *   wl_egl_window_get_attached_size()
```

Would be nice if your script reduce the number of newlines it produces :)

Note: It's similar for other HTML tags.

**Comment by MacroBull** [comment]
Sorry for not working to this repo so long.
I have updated the code, check it out. Problems may be fixed, but the newline before or following the list may not be satisfying.
