### ISSUE TITLE
A short install guide?

### ISSUE THREAD

**Issue by CharlesNepote** [MacroBull/html2zim#2]
Hi,
First of all, thanks for this work.
Could you provide a short documentation how to install html2zim?

I copied the files into ~/.local/share/zim/plugins/
And created a "Custom tool" in zim with the command "clipcli text/html | html2zim -k pathtoimages"
But it doesn't appear to work...

**Comment by MacroBull** [comment]
Well this is NOT a Zim plugin AT ALL, it is just a simple script convert html to Zim schema, the usage is described in readme, it usually works in this flow:
clipboard/html --get_clipboard--> stdin/html --html2zim--> stdout/zim --set_clipboard--> clipboard/zim
So you should configure a clipboard manager app (in KDE it its klipper) to invoke this progress, and you can copy something in browser and paste it into Zim editor.

**Comment by MacroBull** [comment]
You should not use -k in Ubuntu Unity where no KDE component is provided.
You can find some tutorial from the internet about how to run a single python file as one command
